site_name: E4E Mangrove Monitoring 

theme: sandstone


nav:
    - Home: 'index.md'
    - 'About.md'
    - ML: 
        - 'CNN.md'
        - 'UNet.md'
        - 'Semi-Supervised.md'
    - Tools: 
        - 'Labeling Tool.md'
        - 'Image Classification Tool.md'
        - 'GIS Utils.md'
    - Other: 
        - 'Misc.md'
        - 'Papers.md'