site_name: E4E Mangrove Monitoring 

theme: sandstone


nav:
    - Home: 'index.md'
    - 'About.md'
    - ML: 
        - CNN: 'CNN.md'
        - UNet: 'UNet.md'
        - Semi-Supervised: 'Semi-Supervised.md'
    - Tools: 
        - Labeling Tool: 'Labeling Tool.md'
        - Image Classification Tool: 'Image Classification Tool.md'
        - GIS Utils: 'GIS Utils.md'
        - Azure Slack Bot: 'Azure Slackbot.md'
    - Other: 
        - 'Misc.md'
        - 'Papers.md'